# Generated by Django 2.2.8 on 2020-01-08 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tribal', '0003_auto_20200108_2126'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
    ]
