# Generated by Django 2.2.8 on 2020-01-08 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tribal', '0004_remove_product_price'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product',
            new_name='Produce',
        ),
        migrations.RenameField(
            model_name='produce',
            old_name='subcategpry',
            new_name='subcategory',
        ),
    ]
